version: "3"
services:
  mongo:
    image: "mongo"

  mongo-express:
    depends_on:
      - mongo
    image: "mongo-express"
    ports:
      - "8081:8081"

  server:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - PORT=8080
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8080:8080"
